spring:
  application:
    name: pos
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: pos_db
      auto-index-creation: false
  jackson:
    default-property-inclusion: NON_NULL
server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}
